### ISSUE TITLE
Doesn't match named pattern if used in same line where it is declared

### ISSUE THREAD

**Issue by kunalspathak** [CathalMcsweeney/OSSE_Assembly_Search_Project#6]
If I want to search for `mov x0, x0` or `mov x1, x1` , I wanted to specify following pattern:

```
check: mov (?<REG1>x[0-9]+), ?<<REG1>>
```

But with this, I see exception:

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'REG1' was not present in the dictionary.
   at pattern_finder.patternChecker() in E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Program.cs:line 153
   at pattern_finder.heartBeat(String pattern, String assembley) in E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Program.cs:line 119
   at pattern_finder.Main(String[] args) in E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Program.cs:line 40
```

**Comment by kunalspathak** [comment]
Likewise, if accidently a named variable is used without declaring, the tool should give an error asking user to fix the pattern.

```
check: movz (?<REG1>x[0-9]+)
check-next: movk ?<<REG1>>
check-next: movk ?<<REG1>>
check: movz ?<<REG2>>
check-next: movk ?<<REG2>>
check-next: movk ?<<REG2>>

```

```
E:\git\OSSE_Assembly_Search_Project\assembly_patterns>dotnet  E:\git\OSSE_Assembly_Search_Project\assembly_patterns\bin\Release\net6.0\assembly_patterns.dll kpathak-pattern.txt E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Example_Patterns\Assembly_code.txt
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'REG2' was not present in the dictionary.
   at pattern_finder.patternChecker() in E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Program.cs:line 153
   at pattern_finder.heartBeat(String pattern, String assembley) in E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Program.cs:line 119
   at pattern_finder.Main(String[] args) in E:\git\OSSE_Assembly_Search_Project\assembly_patterns\Program.cs:line 40
```
